name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: '10 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 5
    name: Jobs to generate github commit snake
    runs-on: ubuntu-latest
    steps:
      #- name: Generate Snake Animation svg
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Juandbpimentel
          outputs: |
            dist/github-snake.svg
#            dist/github-snake-dark.svg?palette=github-dark
#            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
        name: Push snake to github repository
        if: success()
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
